source ~/bin/bash-color-vars.sh

echo "${RED}\${RED} gives RED RED RED" 
echo "${GREEN}\${GREEN} gives GREEN GREEN GREEN" 
echo "${YELLOW}\${YELLOW} gives YELLOW YELLOW YELLOW" 
echo "${BLUE}\${BLUE} gives BLUE BLUE BLUE" 
echo "${MAGENTA}\${MAGENTA} gives MAGENTA MAGENTA MAGENTA" 
echo "${PURPLE}\${PURPLE} gives PURPLE PURPLE PURPLE" 
echo "${CYAN}\${CYAN} gives CYAN CYAN CYAN" 
echo "${GREY}\${GREY} gives GREY GREY GREY" 
echo "${LRED}\${LRED} gives bold LRED LRED LRED" 
echo "${LGREEN}\${LGREEN} gives bold LGREEN LGREEN LGREEN" 
echo "${LYELLOW}\${LYELLOW} gives bold LYELLOW LYELLOW LYELLOW" 
echo "${LBLUE}\${LBLUE} gives bold LBLUE LBLUE LBLUE" 
echo "${LMAGENTA}\${LMAGENTA} gives bold LMAGENTA LMAGENTA LMAGENTA" 
echo "${LPURPLE}\${LPURPLE} gives bold LPURPLE LPURPLE LPURPLE" 
echo "${LCYAN}\${LCYAN} gives bold LCYAN LCYAN LCYAN" 
echo "${WHITE}\${WHITE} gives bold WHITE WHITE WHITE" 
echo "${RESTORE}\${RESTORE} to go back to normal." 